### PR TITLE
Allow different version to be installed

### PR DESCRIPTION
**Pull request by patrobinson**
Allow version 0.9.0 of wkhtmltopdf to be installed by providing an
optional parameter to the class.

cc @sj26 @johnsyweb

### CODE REVIEW

**Comment by sj26** [comment]
> Oooh, nice idea.

**Comment by sj26** [comment]
Here's a formula for 0.12.2 as well:

https://gist.github.com/sj26/4fbfedc614b4e8859683

This is kinda antithetical to homebrew's philosophy - it's a binary pkg - but it's suuuuper horrible to compile. Ideally this could be bottled I guess?

**Comment by patrobinson** [comment]
Cannot seem to easily mix versions in homebrew... le sigh

**Comment by sj26** [comment]
Ah, because it's distributed as a binary they now host it in caskroom:

https://github.com/caskroom/homebrew-cask/blob/master/Casks/wkhtmltopdf.rb

**Comment by sj26** [comment]
@nemski also, you might like `brew switch <name> <version>`

```
$ brew info wkhtmltopdf
homebrew/boneyard/wkhtmltopdf: stable 0.12.2
http://wkhtmltopdf.org/
/usr/local/Cellar/wkhtmltopdf/0.9.0 (5 files, 344K) *
  Built from source
/usr/local/Cellar/wkhtmltopdf/0.11.0_rc1 (8 files, 744K)
  Built from source
/usr/local/Cellar/wkhtmltopdf/0.12.2 (6 files, 143M)
  Built from source
From: https://github.com/homebrew/homebrew-boneyard/blob/master/wkhtmltopdf.rb

$ brew switch wkhtmltopdf 0.9.0
Cleaning /usr/local/Cellar/wkhtmltopdf/0.11.0_rc1
Cleaning /usr/local/Cellar/wkhtmltopdf/0.12.2
Cleaning /usr/local/Cellar/wkhtmltopdf/0.9.0
2 links created for /usr/local/Cellar/wkhtmltopdf/0.9.0
```

**Comment by sj26** [comment]
I was about to suggest installing legacy versions from the homebrew formulary, but:

```
$ cd /usr/local/Library/Formula
$ git log --oneline --grep wkhtmltopdf
ff8a7aa Move wkhtmltopdf to the boneyard
a355c67 wkhtmltopdf: link against libc++ on Mavericks
aa80fbc wkhtmltopdf 0.11.0_rc1 + fix 64bit compile error
21fd4c9 added wkhtmltopdf 0.9.9 (depends on qt)

$ brew install https://github.com/Homebrew/homebrew/raw/21fd4c9/Library/Formula/wkhtmltopdf.rb
######################################################################## 100.0%
==> Downloading http://wkhtmltopdf.googlecode.com/files/wkhtmltopdf-0.9.9.tar.bz2
######################################################################## 100.0%
Error: MD5 support has been dropped for security reasons.
Please switch this formula to SHA256.
```

Instead you could use those gists I posted:

```
$ brew install https://gist.github.com/sj26/754b404d09a41d35cf05/raw/5adf918f2c7ad843102024d038c9c59710a9d21d/wkhtmltopdf.rb
######################################################################## 100.0%
==> Downloading https://launchpad.net/ubuntu/+archive/primary/+files/wkhtmltopdf_0.9.0.orig.tar.gz
==> Downloading from https://launchpadlibrarian.net/38643065/wkhtmltopdf_0.9.0.orig.tar.gz
######################################################################## 100.0%
==> qmake -spec unsupported/macx-clang-libc++
==> make
🍺  /usr/local/Cellar/wkhtmltopdf/0.9.0: 5 files, 344K, built in 15 seconds

$ brew unlink wkhtmltopdf
Unlinking /usr/local/Cellar/wkhtmltopdf/0.9.0... 2 symlinks removed

$ brew install https://gist.github.com/sj26/4fbfedc614b4e8859683/raw/760be5162b5985df2798a1112893ff210db8b095/wkhtmltopdf.rb
######################################################################## 100.0%
==> Downloading http://download.gna.org/wkhtmltopdf/0.12/0.12.2/wkhtmltox-0.12.2_osx-cocoa-x86-64.pkg
Already downloaded: /Library/Caches/Homebrew/wkhtmltopdf-0.12.2.pkg
Warning: Cannot verify integrity of wkhtmltopdf-0.12.2.pkg
A checksum was not provided for this resource
For your reference the SHA256 is: f53fc73dde8eee05a3a3c05e9666123e5e71fef77b8b658f78801a9a8223b6a9
29607 blocks
x ./
x ./bin/
x ./bin/wkhtmltoimage
x ./bin/wkhtmltopdf
x ./include/
x ./include/wkhtmltox/
x ./include/wkhtmltox/dllbegin.inc
x ./include/wkhtmltox/dllend.inc
x ./include/wkhtmltox/image.h
x ./include/wkhtmltox/pdf.h
x ./lib/
x ./lib/libwkhtmltox.0.12.2.dylib
x ./lib/libwkhtmltox.0.12.dylib
x ./lib/libwkhtmltox.0.dylib
x ./lib/libwkhtmltox.dylib
x ./share/
x ./share/man/
x ./share/man/man1/
x ./share/man/man1/wkhtmltoimage.1.gz
x ./share/man/man1/wkhtmltopdf.1.gz
🍺  /usr/local/Cellar/wkhtmltopdf/0.12.2: 6 files, 143M, built in 2 seconds

$ brew unlink wkhtmltopdf
Unlinking /usr/local/Cellar/wkhtmltopdf/0.12.2... 8 symlinks removed
```

You can do this for any version you fancy, and now you can `brew switch` to whatever. If we were really clever we'd figure out how to do bottles, too.

**Comment by patrobinson** [comment]
This has fallen off the radar for me and there are better solutions around (i.e. docker) that will make this redundant.

**Pull request closed without merging**
